import { CarListing } from "./CardsPage";

export const CarData: CarListing[] = [
  {
    id: 1,
    title: "Mercedes-Benz E350 4Matic Facellift Navi",
    brand: 'Mercedes',
    price: 14000,
    make: 2009,
    fuel: "Diesel",
    mileage: 123000,
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Sapiente officia asperiores facilis eligendi reiciendis nostrum saepe temporibus iure modi optio amet eum ab, iusto eos enim placeat et nesciunt corrupti.  Lorem ipsum dolor sit amet consectetur adipisicing elit. Sapiente officia asperiores facilis eligendi reiciendis nostrum saepe temporibus iure modi optio amet eum ab, iusto eos enim placeat et nesciunt corrupti.",
    sellerType: "Private Seller",
    location: "Varna",
    pictureUrls: [
      "https://c4.wallpaperflare.com/wallpaper/537/50/352/mercedes-benz-amg-black-vossen-wallpaper-preview.jpg",
      "https://wallpapercave.com/wp/wp7896711.jpg",
      "https://p4.wallpaperbetter.com/wallpaper/299/78/483/mercedes-benz-amg-black-vossen-wallpaper-preview.jpg",
      "https://c4.wallpaperflare.com/wallpaper/87/707/680/mercedes-e55-amg-hd-wallpaper-preview.jpg",
      "https://c4.wallpaperflare.com/wallpaper/1020/132/850/mercedes-benz-amg-e55-hd-wallpaper-preview.jpg",
      "https://c4.wallpaperflare.com/wallpaper/327/401/253/2003-amg-e55-mercedes-benz-wallpaper-preview.jpg",
    ],
  },
  {
    id: 2,
    title: "BMW E60 M-pack DSG Steptronic",
    brand: "BMW",
    price: 17000,
    make: 2009,
    fuel: "Diesel",
    mileage: 223000,
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Sapiente officia asperiores facilis eligendi reiciendis nostrum saepe temporibus iure modi optio amet eum ab, iusto eos enim placeat et nesciunt corrupti.",
    sellerType: "Private Seller",
    location: "Varna",
    pictureUrls: [
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQfUBlESTuXu-7qWwfmJMbNjOPtb0Qngsc0bxPTN_bB&s",
      "https://wallpaperaccess.com/full/1600667.jpg",
      "https://wallpaperaccess.com/full/2657155.jpg",
      "https://cdn.wallpapersafari.com/35/83/EohWid.jpg",
      "https://wallpapercrafter.com/desktop/98759-car-BMW-BMW-5-Series-BMW-E60.jpg",
      "https://i.pinimg.com/736x/8f/c7/68/8fc768a3be4832beb4bf1c0c87b3b240.jpg",
    ],
  },
  {
    id: 3,
    title: "Volkswagen Golf 3 GT Gaz/Benzin",
    brand: "Volkswagen",
    price: 2000,
    make: 1998,
    fuel: "Petrol/Gaz",
    mileage: 123000,
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Sapiente officia asperiores facilis eligendi reiciendis nostrum saepe temporibus iure modi optio amet eum ab, iusto eos enim placeat et nesciunt corrupti.Lorem ipsum dolor sit amet consectetur adipisicing elit. Sapiente officia asperiores facilis eligendi reiciendis nostrum saepe temporibus iure modi optio amet eum ab, iusto eos enim placeat et nesciunt corrupti.Lorem ipsum dolor sit amet consectetur adipisicing elit. Sapiente officia asperiores facilis eligendi reiciendis nostrum saepe temporibus iure modi optio amet eum ab, iusto eos enim placeat et nesciunt corrupti.Lorem ipsum dolor sit amet consectetur adipisicing elit. Sapiente officia asperiores facilis eligendi reiciendis nostrum saepe temporibus iure modi optio amet eum ab, iusto eos enim placeat et nesciunt corrupti.",
    sellerType: "Private Seller",
    location: "Varna",
    pictureUrls: [
      "https://fichasmotor.com/images/volkswagen/volkswagen-golf-iii-variant-1hx0-1-8-syncro-90-cv.webp",
      "http://4.bp.blogspot.com/-2tCQNaunmbs/VHdzxzEXfmI/AAAAAAAAB_I/M-pD0bfJ3tM/s1600/2_golf.jpg",
      "https://mobistatic2.focus.bg/mobile/photosmob/787/1/big/11582226708274787_K5.jpg",
      "https://i.pinimg.com/550x/05/05/92/05059297a24ef74a7f60e14606a82785.jpg",
      "https://i.pinimg.com/originals/9b/0b/fe/9b0bfe7fbcb7109894dadac0a7410e07.jpg",
      "https://i.ytimg.com/vi/06P6igE5XFg/maxresdefault.jpg",
    ],
  },
  {
    id: 4,
    title: "Porche Panamera Turbo S GT3",
    brand: "Porche",
    price: 45000,
    make: 2013,
    fuel: "Petrol",
    mileage: 23000,
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Sapiente officia asperiores facilis eligendi reiciendis nostrum saepe temporibus iure modi optio amet eum ab, iusto eos enim placeat et nesciunt corrupti.Lorem ipsum dolor sit amet consectetur adipisicing elit. Sapiente officia asperiores facilis eligendi reiciendis nostrum saepe temporibus iure modi optio amet eum ab, iusto eos enim placeat et nesciunt corrupti.Lorem ipsum dolor sit amet consectetur adipisicing elit. Sapiente officia asperiores facilis eligendi reiciendis nostrum saepe temporibus iure modi optio amet eum ab, iusto eos enim placeat et nesciunt corrupti.Lorem ipsum dolor sit amet consectetur adipisicing elit. Sapiente officia asperiores facilis eligendi reiciendis nostrum saepe temporibus iure modi optio amet eum ab, iusto eos enim placeat et nesciunt corrupti.",
    sellerType: "Private Seller",
    location: "Varna",
    pictureUrls: [
      "https://images.unsplash.com/photo-1611157816410-6a6b31ee255e?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxzZWFyY2h8NHx8cG9yc2NoZSUyMHBhbmFtZXJhfGVufDB8fDB8fA%3D%3D&w=1000&q=80",
      "https://images3.alphacoders.com/857/thumb-1920-857430.jpg",
      "https://cars.usnews.com/static/images/Auto/izmo/i159615107/2022_porsche_panamera_dashboard.jpg",
      "https://www.wsupercars.com/thumbnails/Porsche/2017-Porsche-Panamera-Turbo-002.jpg",
      "https://besthqwallpapers.com/Uploads/1-11-2017/26531/thumb2-porsche-panamera-turbo-s-e-hybrid-2018-sunset-luxury-coupe.jpg",
      "https://prod.pictures.autoscout24.net/listing-images/7b5e51d3-24e1-4e58-ab53-095e70745487_6988bc35-1b94-4a64-92e2-3426b7e7bcaa.jpg/1920x1080.webp",
    ],
  },
  {
    id: 5,
    title: "Audi A6 Avant Sportback Quattro",
    brand: "Audi",
    price: 15000,
    make: 2010,
    fuel: "Petrol",
    mileage: 323000,
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Sapiente officia asperiores facilis eligendi reiciendis nostrum saepe temporibus iure modi optio amet eum ab, iusto eos enim placeat et nesciunt corrupti.Lorem ipsum dolor sit amet consectetur adipisicing elit. Sapiente officia asperiores facilis eligendi reiciendis nostrum saepe temporibus iure modi optio amet eum ab, iusto eos enim placeat et nesciunt corrupti.Lorem ipsum dolor sit amet consectetur adipisicing elit. Sapiente officia asperiores facilis eligendi reiciendis nostrum saepe temporibus iure modi optio amet eum ab, iusto eos enim placeat et nesciunt corrupti.Lorem ipsum dolor sit amet consectetur adipisicing elit. Sapiente officia asperiores facilis eligendi reiciendis nostrum saepe temporibus iure modi optio amet eum ab, iusto eos enim placeat et nesciunt corrupti.",
    sellerType: "Private Seller",
    location: "Varna",
    pictureUrls: [
      "https://img.favcars.com/audi/rs6/pictures_audi_rs6_2008_1_b.jpg",
      "https://www.ultimatecarpage.com/images/car/3336/Audi-RS-6-Avant-25831.jpg",
      "https://img.favcars.com/audi/rs6/audi_rs6_2009_wallpapers_2.jpg",
      "https://www.wsupercars.com/thumbnails/Audi/2009-Audi-RS6-005.jpg",
      "http://cdn.wallpaperhi.com/1920x1080/20121205/video%20games%20vehicles%20audi%20rs6%20gran%20turismo%205%20ps3%201920x1080%20wallpaper_www.wallpaperhi.com_92.jpg",
      "https://www.wsupercars.com/thumbnails/Audi/2009-Audi-RS6-002.jpg",
    ],
  },
  {
    id: 6,
    title: "Volkswagen Golf 7 GTI Facelift",
    brand: "Volkswagen",
    price: 19000,
    make: 2018,
    fuel: "Petrol",
    mileage: 123000,
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Sapiente officia asperiores facilis eligendi reiciendis nostrum saepe temporibus iure modi optio amet eum ab, iusto eos enim placeat et nesciunt corrupti.Lorem ipsum dolor sit amet consectetur adipisicing elit. Sapiente officia asperiores facilis eligendi reiciendis nostrum saepe temporibus iure modi optio amet eum ab, iusto eos enim placeat et nesciunt corrupti.Lorem ipsum dolor sit amet consectetur adipisicing elit. Sapiente officia asperiores facilis eligendi reiciendis nostrum saepe temporibus iure modi optio amet eum ab, iusto eos enim placeat et nesciunt corrupti.Lorem ipsum dolor sit amet consectetur adipisicing elit. Sapiente officia asperiores facilis eligendi reiciendis nostrum saepe temporibus iure modi optio amet eum ab, iusto eos enim placeat et nesciunt corrupti.",
    sellerType: "Private Seller",
    location: "Varna",
    pictureUrls: [
      "https://wallpaperaccess.com/full/3510472.jpg",
      "https://wallpaperaccess.com/full/1886804.jpg",
      "https://wallpapercave.com/wp/wp7662924.jpg",
      "https://wallpaperaccess.com/full/1940686.jpg",
      "https://i.pinimg.com/originals/ed/31/d6/ed31d66cdda73d313160e57e99de1511.jpg",
      "https://w0.peakpx.com/wallpaper/287/305/HD-wallpaper-2017-volkswagen-golf-7-gti-facelift-front-three-quarter-car.jpg",
    ],
  },
  {
    id: 7,
    title: "Volkswagen Passata na Bashtata",
    brand: "Volkswagen",
    price: 11000,
    make: 2009,
    fuel: "Diesel",
    mileage: 123000,
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Sapiente officia asperiores facilis eligendi reiciendis nostrum saepe temporibus iure modi optio amet eum ab, iusto eos enim placeat et nesciunt corrupti.Lorem ipsum dolor sit amet consectetur adipisicing elit. Sapiente officia asperiores facilis eligendi reiciendis nostrum saepe temporibus iure modi optio amet eum ab, iusto eos enim placeat et nesciunt corrupti.Lorem ipsum dolor sit amet consectetur adipisicing elit. Sapiente officia asperiores facilis eligendi reiciendis nostrum saepe temporibus iure modi optio amet eum ab, iusto eos enim placeat et nesciunt corrupti.Lorem ipsum dolor sit amet consectetur adipisicing elit. Sapiente officia asperiores facilis eligendi reiciendis nostrum saepe temporibus iure modi optio amet eum ab, iusto eos enim placeat et nesciunt corrupti.",
    sellerType: "Private Seller",
    location: "Varna",
    pictureUrls: [
      "https://upload.wikimedia.org/wikipedia/commons/thumb/9/91/VW_Passat_B8_Limousine_2.0_TDI_Highline.JPG/800px-VW_Passat_B8_Limousine_2.0_TDI_Highline.JPG",
      "https://hips.hearstapps.com/hmg-prod/images/2021-volkswagen-passat-mmp-1-1597868992.jpg?crop=0.758xw:0.853xh;0.188xw,0.118xh&resize=640:*",
      "https://www.topgear.com/sites/default/files/cars-car/image/2015/01/buyers_guide_-_volkswagen_passat_2014_-_front_quarter_2.jpg?w=1280&h=720",
      "https://www.motortrend.com/uploads/sites/5/2021/07/2022-Volkswagen-Passat-Limited-Edition-11.jpg",
      "https://upload.wikimedia.org/wikipedia/commons/thumb/3/36/VW_Passat_front.JPG/1200px-VW_Passat_front.JPG",
      "https://upload.wikimedia.org/wikipedia/commons/f/fc/Volkswagen_Passat_B6-1.jpg",
    ],
  },
  {
    id: 8,
    title: "Mercedes-Benz S550 W221 Long",
    brand: 'Mercedes',
    price: 24000,
    make: 2009,
    fuel: "Diesel",
    mileage: 323000,
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Sapiente officia asperiores facilis eligendi reiciendis nostrum saepe temporibus iure modi optio amet eum ab, iusto eos enim placeat et nesciunt corrupti.  Lorem ipsum dolor sit amet consectetur adipisicing elit. Sapiente officia asperiores facilis eligendi reiciendis nostrum saepe temporibus iure modi optio amet eum ab, iusto eos enim placeat et nesciunt corrupti.",
    sellerType: "Private Seller",
    location: "Varna",
    pictureUrls: [
      "https://cdn3.focus.bg/autodata/i/mercedes-benz/s-klasse/s-klasse-w221/large/55d3174b58b3490e06e0bfc16da1fd77.jpg",
      "http://www.classic-sterne.de/files/bilder/fahrzeuge/20653%20Mercedes-Benz%20S%20350%20L%20W221%20Schwarz/S350L-W221-Schwarz06.jpg",
      "https://cdn3.focus.bg/autodata/i/mercedes-benz/s-klasse/s-klasse-w221/large/442cd36307a200ff97aeb747c9c9407f.jpg",
      "https://arabam-blog.mncdn.com/wp-content/uploads/2021/05/Mercedes-Benz-W221.jpg",
    ],
  },
  {
    id: 9,
    title: "Mercedes-Benz C320 W203 FACELIFT",
    brand: 'Mercedes',
    price: 18000,
    make: 2012,
    fuel: "Diesel",
    mileage: 273000,
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Sapiente officia asperiores facilis eligendi reiciendis nostrum saepe temporibus iure modi optio amet eum ab, iusto eos enim placeat et nesciunt corrupti.  Lorem ipsum dolor sit amet consectetur adipisicing elit. Sapiente officia asperiores facilis eligendi reiciendis nostrum saepe temporibus iure modi optio amet eum ab, iusto eos enim placeat et nesciunt corrupti.",
    sellerType: "Private Seller",
    location: "Varna",
    pictureUrls: [
      "https://www.auto-data.net/images/f97/Mercedes-Benz-C-class-W204-facelift-2011_1.jpg",
      "https://i.pinimg.com/originals/4a/21/8d/4a218da6dd48377a762ef9ddc1869eba.jpg",
      "https://www.auto-data.net/images/f44/Mercedes-Benz-C-class-W204-facelift-2011_1.jpg",
      "https://cdn.webshopapp.com/shops/258831/files/306789983/image.jpg",
    ],
  },
  {
    id: 10,
    title: "Mercedes-Benz E500 W212 FACELIFT",
    brand: 'Mercedes',
    price: 22000,
    make: 2012,
    fuel: "Diesel",
    mileage: 293000,
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Sapiente officia asperiores facilis eligendi reiciendis nostrum saepe temporibus iure modi optio amet eum ab, iusto eos enim placeat et nesciunt corrupti.  Lorem ipsum dolor sit amet consectetur adipisicing elit. Sapiente officia asperiores facilis eligendi reiciendis nostrum saepe temporibus iure modi optio amet eum ab, iusto eos enim placeat et nesciunt corrupti.",
    sellerType: "Private Seller",
    location: "Varna",
    pictureUrls: [
      "https://maxtondesign.com/eng_pl_Spoiler-Cap-Mercedes-Benz-E63-AMG-AMG-Line-Sedan-W212-Facelift-11694_8.jpg",
      "https://maxtondesign.com/eng_pl_Front-Splitter-V-1-Mercedes-Benz-E-AMG-Line-Sedan-W212-Facelift-15151_6.jpg",
      "https://www.autodata1.com/media/mercedes-benz/pics/mercedes-benz-e-class-w212-facelift-2013-[20322].jpg",
      "https://live.staticflickr.com/3266/3193378303_dfdb21347a_b.jpg",
    ],
  },
  {
    id: 11,
    title: "Mercedes-Benz E300 W213 COUPE",
    brand: 'Mercedes',
    price: 32000,
    make: 2012,
    fuel: "Diesel",
    mileage: 293000,
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Sapiente officia asperiores facilis eligendi reiciendis nostrum saepe temporibus iure modi optio amet eum ab, iusto eos enim placeat et nesciunt corrupti.  Lorem ipsum dolor sit amet consectetur adipisicing elit. Sapiente officia asperiores facilis eligendi reiciendis nostrum saepe temporibus iure modi optio amet eum ab, iusto eos enim placeat et nesciunt corrupti.",
    sellerType: "Private Seller",
    location: "Varna",
    pictureUrls: [
      "https://scl-performance.com/sites/default/files/bodykit_f-soupe_for_mercedes-benz_e-class_soupe_c238_by_scl_global_concept_1.jpg",
      "https://i.ytimg.com/vi/HCN6P-Gm-KE/maxresdefault.jpg",
      "https://i.ytimg.com/vi/_YT2AF6Lvbk/maxresdefault.jpg",
      "https://i.pinimg.com/originals/5d/26/7a/5d267a33d876181563e54f9a9eafd6d2.jpg",
    ],
  },
  {
    id: 12,
    title: "Mercedes-Benz C220 W202 Kombi",
    brand: 'Mercedes',
    price: 5559,
    make: 1999,
    fuel: "Diesel",
    mileage: 393000,
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Sapiente officia asperiores facilis eligendi reiciendis nostrum saepe temporibus iure modi optio amet eum ab, iusto eos enim placeat et nesciunt corrupti.  Lorem ipsum dolor sit amet consectetur adipisicing elit. Sapiente officia asperiores facilis eligendi reiciendis nostrum saepe temporibus iure modi optio amet eum ab, iusto eos enim placeat et nesciunt corrupti.",
    sellerType: "Private Seller",
    location: "Varna",
    pictureUrls: [
      "https://www.goeckel.de/C-K/galerie/w202/Heckspoiler_mercedes_c-klasse_w202_goeckel_sportTE_1.jpg",
      "https://s.kaskus.id/images/fjb/2018/06/06/mercedes_benz_c230_w202_station_wagon_black_1999_7204329_1528303216.jpg",
      "https://mercedes.drive.place/images/mercedes/mercedes_c_klasse_i-res_wagon_5_2.jpg",
      "https://i.pinimg.com/originals/b6/92/c4/b692c41615d0c03f8103451a2a51704e.jpg",
    ],
  },
];
