import { CarListing } from "./CardsPage";

export const CarData: CarListing[] = [
  {
    title: "Mercedes-Benz E350 4Matic Facellift Navi",
    brand: 'Mercedes',
    price: 14000,
    make: 2009,
    fuel: "Diesel",
    mileage: 123000,
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Sapiente officia asperiores facilis eligendi reiciendis nostrum saepe temporibus iure modi optio amet eum ab, iusto eos enim placeat et nesciunt corrupti.  Lorem ipsum dolor sit amet consectetur adipisicing elit. Sapiente officia asperiores facilis eligendi reiciendis nostrum saepe temporibus iure modi optio amet eum ab, iusto eos enim placeat et nesciunt corrupti.",
    sellerType: "Private Seller",
    location: "Varna",
    pictureUrls: [
      "https://c4.wallpaperflare.com/wallpaper/537/50/352/mercedes-benz-amg-black-vossen-wallpaper-preview.jpg",
      "https://wallpapercave.com/wp/wp7896711.jpg",
      "https://p4.wallpaperbetter.com/wallpaper/299/78/483/mercedes-benz-amg-black-vossen-wallpaper-preview.jpg",
      "https://c4.wallpaperflare.com/wallpaper/87/707/680/mercedes-e55-amg-hd-wallpaper-preview.jpg",
      "https://c4.wallpaperflare.com/wallpaper/1020/132/850/mercedes-benz-amg-e55-hd-wallpaper-preview.jpg",
      "https://c4.wallpaperflare.com/wallpaper/327/401/253/2003-amg-e55-mercedes-benz-wallpaper-preview.jpg",
    ],
  },
  {
    title: "BMW E60 M-pack DSG Steptronic",
    brand: "BMW",
    price: 17000,
    make: 2009,
    fuel: "Diesel",
    mileage: 223000,
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Sapiente officia asperiores facilis eligendi reiciendis nostrum saepe temporibus iure modi optio amet eum ab, iusto eos enim placeat et nesciunt corrupti.",
    sellerType: "Private Seller",
    location: "Varna",
    pictureUrls: [
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQfUBlESTuXu-7qWwfmJMbNjOPtb0Qngsc0bxPTN_bB&s",
      "https://wallpaperaccess.com/full/1600667.jpg",
      "https://wallpaperaccess.com/full/2657155.jpg",
      "https://cdn.wallpapersafari.com/35/83/EohWid.jpg",
      "https://wallpapercrafter.com/desktop/98759-car-BMW-BMW-5-Series-BMW-E60.jpg",
      "https://i.pinimg.com/736x/8f/c7/68/8fc768a3be4832beb4bf1c0c87b3b240.jpg",
    ],
  },
  {
    title: "Volkswagen Golf 3 GT Gaz/Benzin",
    brand: "Volkswagen",
    price: 2000,
    make: 1998,
    fuel: "Petrol/Gaz",
    mileage: 123000,
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Sapiente officia asperiores facilis eligendi reiciendis nostrum saepe temporibus iure modi optio amet eum ab, iusto eos enim placeat et nesciunt corrupti.Lorem ipsum dolor sit amet consectetur adipisicing elit. Sapiente officia asperiores facilis eligendi reiciendis nostrum saepe temporibus iure modi optio amet eum ab, iusto eos enim placeat et nesciunt corrupti.Lorem ipsum dolor sit amet consectetur adipisicing elit. Sapiente officia asperiores facilis eligendi reiciendis nostrum saepe temporibus iure modi optio amet eum ab, iusto eos enim placeat et nesciunt corrupti.Lorem ipsum dolor sit amet consectetur adipisicing elit. Sapiente officia asperiores facilis eligendi reiciendis nostrum saepe temporibus iure modi optio amet eum ab, iusto eos enim placeat et nesciunt corrupti.",
    sellerType: "Private Seller",
    location: "Varna",
    pictureUrls: [
      "https://fichasmotor.com/images/volkswagen/volkswagen-golf-iii-variant-1hx0-1-8-syncro-90-cv.webp",
      "http://4.bp.blogspot.com/-2tCQNaunmbs/VHdzxzEXfmI/AAAAAAAAB_I/M-pD0bfJ3tM/s1600/2_golf.jpg",
      "https://mobistatic2.focus.bg/mobile/photosmob/787/1/big/11582226708274787_K5.jpg",
      "https://i.pinimg.com/550x/05/05/92/05059297a24ef74a7f60e14606a82785.jpg",
      "https://i.pinimg.com/originals/9b/0b/fe/9b0bfe7fbcb7109894dadac0a7410e07.jpg",
      "https://i.ytimg.com/vi/06P6igE5XFg/maxresdefault.jpg",
    ],
  },
  {
    title: "Porche Panamera Turbo S GT3",
    brand: "Porche",
    price: 45000,
    make: 2013,
    fuel: "Petrol",
    mileage: 23000,
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Sapiente officia asperiores facilis eligendi reiciendis nostrum saepe temporibus iure modi optio amet eum ab, iusto eos enim placeat et nesciunt corrupti.Lorem ipsum dolor sit amet consectetur adipisicing elit. Sapiente officia asperiores facilis eligendi reiciendis nostrum saepe temporibus iure modi optio amet eum ab, iusto eos enim placeat et nesciunt corrupti.Lorem ipsum dolor sit amet consectetur adipisicing elit. Sapiente officia asperiores facilis eligendi reiciendis nostrum saepe temporibus iure modi optio amet eum ab, iusto eos enim placeat et nesciunt corrupti.Lorem ipsum dolor sit amet consectetur adipisicing elit. Sapiente officia asperiores facilis eligendi reiciendis nostrum saepe temporibus iure modi optio amet eum ab, iusto eos enim placeat et nesciunt corrupti.",
    sellerType: "Private Seller",
    location: "Varna",
    pictureUrls: [
      "https://images.unsplash.com/photo-1611157816410-6a6b31ee255e?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxzZWFyY2h8NHx8cG9yc2NoZSUyMHBhbmFtZXJhfGVufDB8fDB8fA%3D%3D&w=1000&q=80",
      "https://images3.alphacoders.com/857/thumb-1920-857430.jpg",
      "https://cars.usnews.com/static/images/Auto/izmo/i159615107/2022_porsche_panamera_dashboard.jpg",
      "https://www.wsupercars.com/thumbnails/Porsche/2017-Porsche-Panamera-Turbo-002.jpg",
      "https://besthqwallpapers.com/Uploads/1-11-2017/26531/thumb2-porsche-panamera-turbo-s-e-hybrid-2018-sunset-luxury-coupe.jpg",
      "https://prod.pictures.autoscout24.net/listing-images/7b5e51d3-24e1-4e58-ab53-095e70745487_6988bc35-1b94-4a64-92e2-3426b7e7bcaa.jpg/1920x1080.webp",
    ],
  },
  {
    title: "Audi A6 Avant Sportback Quattro",
    brand: "Audi",
    price: 15000,
    make: 2010,
    fuel: "Petrol",
    mileage: 323000,
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Sapiente officia asperiores facilis eligendi reiciendis nostrum saepe temporibus iure modi optio amet eum ab, iusto eos enim placeat et nesciunt corrupti.Lorem ipsum dolor sit amet consectetur adipisicing elit. Sapiente officia asperiores facilis eligendi reiciendis nostrum saepe temporibus iure modi optio amet eum ab, iusto eos enim placeat et nesciunt corrupti.Lorem ipsum dolor sit amet consectetur adipisicing elit. Sapiente officia asperiores facilis eligendi reiciendis nostrum saepe temporibus iure modi optio amet eum ab, iusto eos enim placeat et nesciunt corrupti.Lorem ipsum dolor sit amet consectetur adipisicing elit. Sapiente officia asperiores facilis eligendi reiciendis nostrum saepe temporibus iure modi optio amet eum ab, iusto eos enim placeat et nesciunt corrupti.",
    sellerType: "Private Seller",
    location: "Varna",
    pictureUrls: [
      "https://img.favcars.com/audi/rs6/pictures_audi_rs6_2008_1_b.jpg",
      "https://www.ultimatecarpage.com/images/car/3336/Audi-RS-6-Avant-25831.jpg",
      "https://img.favcars.com/audi/rs6/audi_rs6_2009_wallpapers_2.jpg",
      "https://www.wsupercars.com/thumbnails/Audi/2009-Audi-RS6-005.jpg",
      "http://cdn.wallpaperhi.com/1920x1080/20121205/video%20games%20vehicles%20audi%20rs6%20gran%20turismo%205%20ps3%201920x1080%20wallpaper_www.wallpaperhi.com_92.jpg",
      "https://www.wsupercars.com/thumbnails/Audi/2009-Audi-RS6-002.jpg",
    ],
  },
  {
    title: "Volkswagen Golf 7 GTI Facelift",
    brand: "Volkswagen",
    price: 19000,
    make: 2018,
    fuel: "Petrol",
    mileage: 123000,
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Sapiente officia asperiores facilis eligendi reiciendis nostrum saepe temporibus iure modi optio amet eum ab, iusto eos enim placeat et nesciunt corrupti.Lorem ipsum dolor sit amet consectetur adipisicing elit. Sapiente officia asperiores facilis eligendi reiciendis nostrum saepe temporibus iure modi optio amet eum ab, iusto eos enim placeat et nesciunt corrupti.Lorem ipsum dolor sit amet consectetur adipisicing elit. Sapiente officia asperiores facilis eligendi reiciendis nostrum saepe temporibus iure modi optio amet eum ab, iusto eos enim placeat et nesciunt corrupti.Lorem ipsum dolor sit amet consectetur adipisicing elit. Sapiente officia asperiores facilis eligendi reiciendis nostrum saepe temporibus iure modi optio amet eum ab, iusto eos enim placeat et nesciunt corrupti.",
    sellerType: "Private Seller",
    location: "Varna",
    pictureUrls: [
      "https://wallpaperaccess.com/full/3510472.jpg",
      "https://wallpaperaccess.com/full/1886804.jpg",
      "https://wallpapercave.com/wp/wp7662924.jpg",
      "https://wallpaperaccess.com/full/1940686.jpg",
      "https://i.pinimg.com/originals/ed/31/d6/ed31d66cdda73d313160e57e99de1511.jpg",
      "https://w0.peakpx.com/wallpaper/287/305/HD-wallpaper-2017-volkswagen-golf-7-gti-facelift-front-three-quarter-car.jpg",
    ],
  },
  {
    title: "Volkswagen Passata na Bashtata",
    brand: "Volkswagen",
    price: 11000,
    make: 2009,
    fuel: "Diesel",
    mileage: 123000,
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Sapiente officia asperiores facilis eligendi reiciendis nostrum saepe temporibus iure modi optio amet eum ab, iusto eos enim placeat et nesciunt corrupti.Lorem ipsum dolor sit amet consectetur adipisicing elit. Sapiente officia asperiores facilis eligendi reiciendis nostrum saepe temporibus iure modi optio amet eum ab, iusto eos enim placeat et nesciunt corrupti.Lorem ipsum dolor sit amet consectetur adipisicing elit. Sapiente officia asperiores facilis eligendi reiciendis nostrum saepe temporibus iure modi optio amet eum ab, iusto eos enim placeat et nesciunt corrupti.Lorem ipsum dolor sit amet consectetur adipisicing elit. Sapiente officia asperiores facilis eligendi reiciendis nostrum saepe temporibus iure modi optio amet eum ab, iusto eos enim placeat et nesciunt corrupti.",
    sellerType: "Private Seller",
    location: "Varna",
    pictureUrls: [
      "https://upload.wikimedia.org/wikipedia/commons/thumb/9/91/VW_Passat_B8_Limousine_2.0_TDI_Highline.JPG/800px-VW_Passat_B8_Limousine_2.0_TDI_Highline.JPG",
      "https://hips.hearstapps.com/hmg-prod/images/2021-volkswagen-passat-mmp-1-1597868992.jpg?crop=0.758xw:0.853xh;0.188xw,0.118xh&resize=640:*",
      "https://www.topgear.com/sites/default/files/cars-car/image/2015/01/buyers_guide_-_volkswagen_passat_2014_-_front_quarter_2.jpg?w=1280&h=720",
      "https://www.motortrend.com/uploads/sites/5/2021/07/2022-Volkswagen-Passat-Limited-Edition-11.jpg",
      "https://upload.wikimedia.org/wikipedia/commons/thumb/3/36/VW_Passat_front.JPG/1200px-VW_Passat_front.JPG",
      "https://upload.wikimedia.org/wikipedia/commons/f/fc/Volkswagen_Passat_B6-1.jpg",
    ],
  },
];
